name: Run Windmill Forecasting Notebooks

on:
  schedule:
    - cron: "0 3 * * *"  # Runs every day at 3 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Adjust Python version if needed

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter  # Explicitly install Jupyter

      - name: Run Windmill Energy Prediction Notebook
        run: |
          python -m jupyter nbconvert --to notebook --execute WindmillEnergyPredn.ipynb --inplace

      - name: Run Windmill Forecasting Notebook
        run: |
          python -m jupyter nbconvert --to notebook --execute WindmillForecasting.ipynb --inplace

      - name: Commit and Push Updated CSV and Image
        run: |
          git config --local user.email "ashmansodhi@hotmail.com"
          git config --local user.name "Ashman Sodhi"
          git add -A  # Add updated CSV and image files
          git commit -m "Automated update of CSV and image at 3 AM" || echo "No changes to commit"
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
